version: "3.8"

services:
  pixelarium:
    container_name: pixelarium
    build: .
    env_file:
      - .env
      - .env.dev
      - .env.staging
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
      - .env.dev
      - .env.staging
    volumes:
      - data_postgres:/database/postgres/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}

volumes:
  data_postgres:
